export const BAD_PRODUCT = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const BAD_WEBSITE_PRODUCT = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const BAD_PAID_SEARCH_PRODUCT = {
  Partner: 'B',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_UNKNOWN = {
  Partner: 'PARTNER_UNKNOWN',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  LineItems: [
    {
      ID: 1,
      ProductID: 'sample string 17',
      ProductType: 'sample string 18',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
    {
      ID: 1,
      ProductID: '6789',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_A_CORRECT = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_A_INCOMPLETE_1 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_INCOMPLETE_2 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_INCOMPLETE_3 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_INCOMPLETE_4 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_INCOMPLETE_5 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_INCOMPLETE_6 = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
    },
  ],
};

export const PARTNER_A_WRONG_PRODUCT = {
  Partner: 'A',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_B_CORRECT = {
  Partner: 'B',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
    {
      ProductID: 'sample string 17',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_B_WRONG_PRODUCT = {
  Partner: 'B',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ContactFirstName: 'C',
  ContactLastName: 'C',
  ContactTitle: 'C',
  ContactPhone: 'C',
  ContactMobile: 'C',
  ContactEmail: 'C',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
    {
      ProductID: 'sample string 17',
      ProductType: 'Jafar Product',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_C_CORRECT = {
  Partner: 'C',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ExposureID: 'string',
  UDAC: 'string',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
    {
      ProductID: 'sample string 17',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_C_WRONG_1 = {
  Partner: 'C',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  UDAC: 'string',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_C_WRONG_2 = {
  Partner: 'C',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ExposureID: 'string',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_C_WRONG_3 = {
  Partner: 'C',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ExposureID: 'string',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website_MebSite',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_C_WRONG_RELATED_ORDER = {
  Partner: 'C',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  ExposureID: 'string',
  UDAC: 'string',
  RelatedOrder: '99313a4d-da5e-4c10-99bf-f9ca2a8c32f1',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      WebsiteDetails: {
        TemplateId: 'sample string 245',
        WebsiteBusinessName: 'sample string 245',
        WebsiteAddressLine1: 'sample string 246',
        WebsiteAddressLine2: 'sample string 247',
        WebsiteCity: 'sample string 248',
        WebsiteState: 'sample string 249',
        WebsitePostCode: 'sample string 250',
        WebsitePhone: 'sample string 257',
        WebsiteEmail: 'sample string 258',
        WebsiteMobile: 'sample string 259',
      },
    },
  ],
};

export const PARTNER_D_CORRECT = {
  Partner: 'D',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Paid Search',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};

export const PARTNER_D_WRONG_PRODUCT = {
  Partner: 'D',
  OrderID: 'sample string 7',
  TypeOfOrder: 'sample string 8',
  SubmittedBy: 'sample string 11',
  CompanyID: 'sample string 28',
  CompanyName: 'sample string 29',
  LineItems: [
    {
      ProductID: 'sample string 17',
      ProductType: 'Website',
      Notes: 'sample string 53',
      Category: 'sample string 245',
      AdWordCampaign: {
        CampaignName: 'sample string 1',
        CampaignAddressLine1: 'sample string 2',
        CampaignPostCode: 'sample string 6',
        CampaignRadius: 'sample string 13',
        LeadPhoneNumber: 'sample string 14',
        SMSPhoneNumber: 'sample string 15',
        UniqueSellingPoint1: 'sample string 18',
        UniqueSellingPoint2: 'sample string 19',
        UniqueSellingPoint3: 'sample string 20',
        Offer: 'sample string 21',
        DestinationURL: 'sample string 23',
      },
    },
  ],
};
