language: node_js
node_js:
  - 12.13.0
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database simple_order_test;' -U postgres
script:
  - yarn test
  - yarn coveralls

deploy:
  provider: script
  script: bash ./publish-docker.sh $TRAVIS_BRANCH
  on:
    condition: $TRAVIS_BRANCH =~ ^(develop|master|)$
